language: go

sudo: false

go:
  - "1.12.x"
  - tip

before_install:
   sudo service redis-server start --bind 127.0.0.1

install:
  - GO111MODULE=on go mod download

script:
  - GO111MODULE=on go test -v ./...

matrix:
  allow_failures:
    - go: tip
